# Generated by Django 3.0.7 on 2020-06-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.TextField(blank=True, null=True)),
                ('old_price', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/malin/vendor_images')),
                ('time', models.DateTimeField()),
                ('time_update', models.DateTimeField()),
                ('visibility', models.IntegerField(blank=True, null=True)),
                ('shop_categorie', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('order_limits', models.IntegerField(blank=True, null=True)),
                ('unit_measurement', models.TextField(blank=True, null=True)),
                ('procurement', models.IntegerField(blank=True, null=True)),
                ('in_slider', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('virtual_products', models.IntegerField(blank=True, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
